import { google } from "googleapis";
import { prisma } from "@/lib/prisma";

function getSheetsClient() {
  const clientEmail = process.env.GOOGLE_SHEETS_CLIENT_EMAIL;
  const privateKey = process.env.GOOGLE_SHEETS_PRIVATE_KEY?.replace(/\\n/g, "\n");

  if (!clientEmail || !privateKey) {
    throw new Error("Google Sheets credentials are not configured");
  }

  const auth = new google.auth.JWT({
    email: clientEmail,
    key: privateKey,
    scopes: ["https://www.googleapis.com/auth/spreadsheets"],
  });

  return google.sheets({ version: "v4", auth });
}

async function writeSheet(spreadsheetId: string, range: string, rows: unknown[][]) {
  const sheets = getSheetsClient();

  await sheets.spreadsheets.values.clear({ spreadsheetId, range });
  await sheets.spreadsheets.values.update({
    spreadsheetId,
    range: `${range}!A1`,
    valueInputOption: "RAW",
    requestBody: { values: rows },
  });
}

/**
 * Exports leads, deals, revenue, and P&L data to dedicated tabs in the
 * configured Google Sheets spreadsheet for external reporting.
 */
export async function syncToGoogleSheets() {
  const spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;
  if (!spreadsheetId) {
    throw new Error("GOOGLE_SHEETS_SPREADSHEET_ID is not configured");
  }

  const [leads, deals, revenueLogs, pnl] = await Promise.all([
    prisma.lead.findMany({
      include: { generatedBy: true, assignedCloser: true },
      orderBy: { createdAt: "desc" },
    }),
    prisma.deal.findMany({
      include: { assignedCloser: true, assignedDesigner: true },
      orderBy: { createdAt: "desc" },
    }),
    prisma.revenueLog.findMany({
      include: { deal: true, handledBy: true },
      orderBy: { dateReceived: "desc" },
    }),
    prisma.monthlyPnL.findMany({ orderBy: [{ year: "desc" }, { month: "desc" }] }),
  ]);

  const leadRows = [
    ["Client Name", "Company", "Service Needed", "Source", "Status", "Generated By", "Closer", "Created At"],
    ...leads.map((l) => [
      l.clientName,
      l.companyName ?? "",
      l.serviceNeeded,
      l.leadSource,
      l.leadStatus,
      l.generatedBy?.fullName ?? "",
      l.assignedCloser?.fullName ?? "",
      l.createdAt.toISOString(),
    ]),
  ];

  const dealRows = [
    ["Deal Name", "Service Type", "Stage", "Priority", "Deal Value", "Balance Status", "Closer", "Designer", "Created At"],
    ...deals.map((d) => [
      d.dealName,
      d.serviceType,
      d.dealStage,
      d.priority,
      d.dealValue.toNumber(),
      d.balanceStatus,
      d.assignedCloser?.fullName ?? "",
      d.assignedDesigner?.fullName ?? "",
      d.createdAt.toISOString(),
    ]),
  ];

  const revenueRows = [
    ["Deal", "Amount Received", "Payment Type", "Payment Method", "Confirmed", "Date Received", "Handled By"],
    ...revenueLogs.map((r) => [
      r.deal?.dealName ?? "",
      r.amountReceived.toNumber(),
      r.paymentType,
      r.paymentMethod,
      r.confirmed ? "Yes" : "No",
      r.dateReceived.toISOString(),
      r.handledBy?.fullName ?? "",
    ]),
  ];

  const pnlRows = [
    ["Month", "Year", "Revenue", "Fixed Expenses", "Variable Expenses", "Salary Payouts", "Net Profit", "Margin %"],
    ...pnl.map((p) => [
      p.month,
      p.year,
      p.totalRevenue.toNumber(),
      p.totalFixedExpenses.toNumber(),
      p.totalVariableExpenses.toNumber(),
      p.totalSalaryPayouts.toNumber(),
      p.netProfit.toNumber(),
      p.profitMarginPct.toNumber(),
    ]),
  ];

  await Promise.all([
    writeSheet(spreadsheetId, "Leads", leadRows),
    writeSheet(spreadsheetId, "Deals", dealRows),
    writeSheet(spreadsheetId, "Revenue", revenueRows),
    writeSheet(spreadsheetId, "P&L", pnlRows),
  ]);

  return {
    leads: leads.length,
    deals: deals.length,
    revenueLogs: revenueLogs.length,
    pnl: pnl.length,
  };
}
