"use client";

import { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Pencil, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { LeadForm } from "@/components/leads/LeadForm";
import { useLead, useDeleteLead } from "@/hooks/useLeads";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import {
  LEAD_SOURCE_LABELS,
  LEAD_STATUS_LABELS,
  SERVICE_TYPE_LABELS,
  DEAL_STAGE_LABELS,
} from "@/lib/constants";
import { formatCurrency } from "@/lib/utils";
import { UserRole } from "@/types/enums";

export default function LeadDetailPage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const { toast } = useToast();
  const { teamMember } = useAuth();
  const { data: lead, isLoading } = useLead(params.id);
  const deleteLead = useDeleteLead();
  const [formOpen, setFormOpen] = useState(false);

  if (isLoading || !lead) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-8 w-48" />
        <Skeleton className="h-48 w-full" />
      </div>
    );
  }

  const canEdit =
    teamMember?.role === UserRole.ADMIN ||
    (teamMember?.role === UserRole.LEAD_GENERATOR && lead.generatedById === teamMember.id) ||
    (teamMember?.role === UserRole.SALES_CLOSER && lead.assignedCloserId === teamMember.id);

  async function handleDelete() {
    if (!confirm("Delete this lead? This cannot be undone.")) return;
    try {
      await deleteLead.mutateAsync(lead!.id);
      toast({ title: "Lead deleted" });
      router.push("/leads");
    } catch (error: any) {
      toast({ title: "Error", description: error.message, variant: "destructive" });
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <Button variant="ghost" onClick={() => router.push("/leads")}>
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Leads
        </Button>
        {canEdit && (
          <div className="flex gap-2">
            <Button variant="outline" onClick={() => setFormOpen(true)}>
              <Pencil className="mr-2 h-4 w-4" />
              Edit
            </Button>
            {teamMember?.role === UserRole.ADMIN && (
              <Button variant="destructive" onClick={handleDelete}>
                <Trash2 className="mr-2 h-4 w-4" />
                Delete
              </Button>
            )}
          </div>
        )}
      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-lg">{lead.clientName}</CardTitle>
            <Badge>{LEAD_STATUS_LABELS[lead.leadStatus]}</Badge>
          </div>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          <Field label="Company" value={lead.companyName ?? "—"} />
          <Field label="Discord Username" value={lead.discordUsername} />
          <Field label="Contact Info" value={lead.contactInfo ?? "—"} />
          <Field label="Service Needed" value={SERVICE_TYPE_LABELS[lead.serviceNeeded]} />
          <Field label="Lead Source" value={LEAD_SOURCE_LABELS[lead.leadSource]} />
          <Field label="Generated By" value={lead.generatedBy?.fullName ?? "—"} />
          <Field label="Assigned Closer" value={lead.assignedCloser?.fullName ?? "Unassigned"} />
          <Field label="Created" value={new Date(lead.createdAt).toLocaleDateString()} />
          {lead.notes && (
            <div className="sm:col-span-2">
              <p className="text-sm text-muted-foreground">Notes</p>
              <p className="text-sm mt-1 whitespace-pre-wrap">{lead.notes}</p>
            </div>
          )}
        </CardContent>
      </Card>

      {lead.deals && lead.deals.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="text-base">Related Deals</CardTitle>
          </CardHeader>
          <CardContent className="space-y-2">
            {lead.deals.map((deal) => (
              <div
                key={deal.id}
                className="flex items-center justify-between rounded-lg border border-white/[0.06] p-3 cursor-pointer transition-colors hover:bg-blue-500/[0.06] hover:border-white/10"
                onClick={() => router.push(`/deals/${deal.id}`)}
              >
                <div>
                  <p className="font-medium">{deal.dealName}</p>
                  <p className="text-sm text-muted-foreground">
                    {DEAL_STAGE_LABELS[deal.dealStage]}
                  </p>
                </div>
                <p className="font-medium">{formatCurrency(deal.dealValue)}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      <LeadForm open={formOpen} onOpenChange={setFormOpen} lead={lead} />
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-sm text-muted-foreground">{label}</p>
      <p className="text-sm font-medium mt-1">{value}</p>
    </div>
  );
}
